# Generated by Django 3.2.3 on 2021-05-21 07:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content_id',
            new_name='object_id',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='content_id',
            new_name='object_id',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('object_id', 'content_type', 'user')},
        ),
    ]
